name = "SSSmatrices"
uuid = "3412c098-c7a3-42a8-8559-4c2813e613ac"
authors = ["Nithin Govindarajan <nithin.govindarajan@gmail.com>"]
version = "0.1.0"

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
